name: "Camera PTZ Control"
version: "1.0.3"
slug: "camera_ptz_control"
description: "Control PTZ camera movements and take pictures via API"
url: "https://github.com/asecashugo/plate_cv"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
ports:
  8000/tcp: 8000
init: false
options:
  camera_ip: "192.168.1.139"
schema:
  camera_ip: str
  password: password?
advanced: true
stage: experimental
auth_api: true
hassio_api: true
hassio_role: default
